title: Justin Gamble
description: Tapping into the Elixir mindset

url: "https://justingamble.github.io"

# caymon-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
    date_format: "%b %-d, %Y"

port: 4444

theme:   # leave it empty

first_name: Justin

linkedin:
  username: justin-gamble-6762391

twitter:
  username: JustinGamble50

defaults:
    - scope:
          path: "assets/images"
      values:
          image: true
